# Generated by Django 3.1.7 on 2021-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
