# Generated by Django 3.1.7 on 2021-07-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210720_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
        migrations.RenameModel(
            old_name='Texts',
            new_name='Text',
        ),
    ]
