# Generated by Django 3.1.7 on 2021-07-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210720_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='media_cdn'),
        ),
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
