# Generated by Django 3.1.7 on 2021-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_text_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_nubmer',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tittle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
