# Generated by Django 3.1.7 on 2021-08-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210803_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, default=False, upload_to='media_cdn'),
        ),
    ]
