# Generated by Django 3.1.7 on 2021-08-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20210803_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.FileField(blank=True, default=None, upload_to='media_cdn'),
        ),
    ]
